# ---
# - hosts: localhost
#   tasks:
#   - name: Print debug message
#     debug:
#       msg: Hello, world!
      
# ---
# - name: Create ticket with notes
#   hosts: localhost
#   gather_facts: no
#   connection: local
#   tasks:
#   - name: include vars
#     include_vars: change_request_vars.yml

#   - name: Create a change request
#     snow_record:
#       state: present
#       table: change_request
#       username: "{{ sn_username }}"
#       password: "{{ sn_password }}"
#       instance: "{{ sn_instance }}"
#       data:
#         severity: "{{ sn_severity }}"
#         priority: "{{ sn_priority }}"
#         short_description: "This is a test opened by Ansible"
#     register: new_incident


# ---
# - hosts: localhost
#   tasks:
#   - name: Create an incident
#     servicenow.servicenow.snow_record:
#       username: admin
#       password: O$qBEotr8=3T
#       instance: dev90863
#       state: present
#       data:
#         short_description: "This is a test incident opened by Ansible"
#         severity: 3
#         priority: 2
#     register: new_incident

---
- hosts: all
  tasks:
  - name: Print Hello World
    debug: msg="Hello World"
